CREATE TABLE t_user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(50) NOT NULL,
   username VARCHAR(25) NOT NULL,
   password VARCHAR(255) NOT NULL,
   email VARCHAR(255),
   role INTEGER,
   active BOOLEAN DEFAULT TRUE NOT NULL,
   created_at TIMESTAMP WITHOUT TIME ZONE,
   updated_at TIMESTAMP WITHOUT TIME ZONE,
   CONSTRAINT pk_t_user PRIMARY KEY (id)
);

ALTER TABLE t_user ADD CONSTRAINT uc_t_user_email UNIQUE (email);

ALTER TABLE t_user ADD CONSTRAINT uc_t_user_username UNIQUE (username);

INSERT INTO t_user(name, username, password, role) VALUES
('Administrator', 'admin', '$2a$12$6tCUFEczTC/O0x9dMGkV3unOAgutEuk.uXqbcTL9bllOJrkzPYMYS', 1),
('Employee', 'employee', '$2a$12$6tCUFEczTC/O0x9dMGkV3unOAgutEuk.uXqbcTL9bllOJrkzPYMYS', 2);