CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(25) NOT NULL,
   description TEXT,
   created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
   CONSTRAINT pk_categories PRIMARY KEY (id)
);

ALTER TABLE categories ADD CONSTRAINT uc_categories_name UNIQUE (name);

INSERT INTO categories (name, description) VALUES
('FOOD', 'Food Category Description'),
('DRINK', 'Drink Category Description'),
('COFFEE', 'Coffee Category Description');